import { Movie } from "../models/Movie";
const movies: Movie[] = <Movie[]>(<unknown>[
  {
    posterPath: null,
    overview:
      'Go behind the scenes during One Directions sell out "Take Me Home" tour and experience life on the road.',
    releaseDate: "2013-08-30",
    genres: [99, 10402],
    id: 164558,
    originalTitle: "One Direction: This Is Us",
    title: "One Direction: This Is Us",
    tagline: "Tagline generic: One Direction: This Is Us",
    voteAverage: 1.1,
    voteCount: 55,
    popularity: 8,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
    actors: null,
    companies: null,
  },
  {
    posterPath: null,
    overview: "On the Waterfront",
    releaseDate: "1954-06-22",
    genres: [80, 18],
    id: 654,
    originalTitle: "On the Waterfront",
    title: "On the Waterfront",
    tagline: "Tagline generic: On the Waterfront",
    voteAverage: 1.5,
    voteCount: 51,
    popularity: 8.19,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "A team of allied saboteurs are assigned an impossible mission: infiltrate an impregnable Nazi-held island and destroy the two enormous long-range field guns that prevent the rescue of 2,000 trapped British soldiers.",
    releaseDate: "1961-04-27",
    genres: [28, 18, 12, 10752],
    id: 10911,
    originalTitle: "The Guns of Navarone",
    title: "The Guns of Navarone",
    tagline: "Tagline generic: The Guns of Navarone",
    voteAverage: 1.0,
    voteCount: 50,
    popularity: 7.56,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "The defendant In a murder trial says that he suffered temporary insanity after the victim had raped his wife. What is the truth, is his attorney being played, and will he win his case?",
    releaseDate: "1959-07-01",
    genres: [80, 18, 9648, 53],
    id: 93,
    originalTitle: "Anatomy of a Murder",
    title: "Anatomy of a Murder",
    tagline: "Tagline generic: Anatomy of a Murder",
    voteAverage: 1.5,
    voteCount: 37,
    popularity: 7.45,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "Ellie Andrews has just tied the knot with society aviator King Westley when she is whisked away to her father's yacht and out of King's clutches. Ellie jumps ship and eventually winds up on a bus headed back to her husband. Reluctantly she must accept the help of out-of- work reporter Peter Warne. Actually, Warne doesn't give her any choice: either she sticks with him until he gets her back to her husband, or he'll blow the whistle on Ellie to her father. Either way, Peter gets what he wants... a really juicy newspaper story!",
    releaseDate: "1934-02-22",
    genres: [35, 10749],
    id: 3078,
    originalTitle: "It Happened One Night",
    title: "It Happened One Night",
    tagline: "Tagline generic: It Happened One Night",
    voteAverage: 1.0,
    voteCount: 48,
    popularity: 7.3,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "Lawrence of Arabia is the classic film from David Lean starring Peter O’Toole and based on the autobiography from Thomas Edward Lawrence who during the first World War was on assignment by the British Empire in Arabia. The film would become a cult classic and is known today as a masterpiece.",
    releaseDate: "1962-12-10",
    genres: [12, 18, 36, 10752],
    id: 947,
    originalTitle: "Lawrence of Arabia",
    title: "Lawrence of Arabia",
    tagline: "Tagline generic: Lawrence of Arabia",
    voteAverage: 1.0,
    voteCount: 269,
    popularity: 7.23,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "Hildy Johnson has divorced Walter Burns and visits his office to tell him that she is engaged to another man and that they are going to get married the day after. Walter Burns can't let that happen and frames the other man, Bruce Baldwin, for a lot of stuff getting him into trouble all the time, while he tries to steer Hildy back into her old job as his employee (editor of his newspaper).",
    releaseDate: "1940-01-11",
    genres: [35, 18, 10749],
    id: 3085,
    originalTitle: "His Girl Friday",
    title: "His Girl Friday",
    tagline: "Tagline generic: His Girl Friday",
    voteAverage: 1.0,
    voteCount: 20,
    popularity: 7.2,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "Tough cop Dave Bannion takes on a politically powerful crime syndicate.",
    releaseDate: "1953-10-14",
    genres: [80, 18],
    id: 14580,
    originalTitle: "The Big Heat",
    title: "The Big Heat",
    tagline: "Tagline generic: The Big Heat",
    voteAverage: 1.5,
    voteCount: 10,
    popularity: 7.2,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "Rich Mr. Dashwood dies, leaving his second wife and her daughters poor by the rules of inheritance. Two daughters are the titular opposites.",
    releaseDate: "1995-12-13",
    genres: [18, 10749],
    id: 4584,
    originalTitle: "Sense and Sensibility",
    title: "Sense and Sensibility",
    tagline: "Tagline generic: Sense and Sensibility",
    voteAverage: 1.1,
    voteCount: 82,
    popularity: 7.15,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "Ted Kramer is a career man for whom his work comes before his family. His wife Joanna cannot take this anymore, so she decides to leave him. Ted is now faced with the tasks of housekeeping and taking care of himself and their young son Billy. When he has learned to adjust his life to these new responsibilities, Joanna resurfaces and wants Billy back. Ted however refuses to give him up, so they go to court to fight for the custody of their son.",
    releaseDate: "1979-12-19",
    genres: [18],
    id: 12102,
    originalTitle: "Kramer vs. Kramer",
    title: "Kramer vs. Kramer",
    tagline: "Tagline generic: Kramer vs. Kramer",
    voteAverage: 1.0,
    voteCount: 68,
    popularity: 7.15,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "A rule bound head butler's world of manners and decorum in the household he maintains is tested by the arrival of a housekeeper who falls in love with him in post-WWI Britain. The possibility of romance and his master's cultivation of ties with the Nazi cause challenge his carefully maintained veneer of servitude.",
    releaseDate: "1993-11-12",
    genres: [18, 10749],
    id: 1245,
    originalTitle: "The Remains of the Day",
    title: "The Remains of the Day",
    tagline: "Tagline generic: The Remains of the Day",
    voteAverage: 1.0,
    voteCount: 37,
    popularity: 7.11,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "Tale of 19th century New York high society in which a young lawyer falls in love with a woman separated from her husband, while he is engaged to the woman's cousin.",
    releaseDate: "1993-09-17",
    genres: [18, 10749],
    id: 10436,
    originalTitle: "The Age of Innocence",
    title: "The Age of Innocence",
    tagline: "Tagline generic: The Age of Innocence",
    voteAverage: 1.0,
    voteCount: 26,
    popularity: 7.06,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "And Now for Something Completely Different is a film spin-off from the television comedy series Monty Python's Flying Circus featuring favourite sketches from the first two seasons.",
    releaseDate: "1971-09-28",
    genres: [35],
    id: 9267,
    originalTitle: "And Now for Something Completely Different",
    title: "And Now for Something Completely Different",
    tagline: "Tagline generic: And Now for Something Completely Different",
    voteAverage: 1.0,
    voteCount: 25,
    popularity: 6.98,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "A narcissistic TV weatherman, along with his attractive-but-distant producer and mawkish cameraman, is sent to report on Groundhog Day in the small town of Punxsutawney, where he finds himself repeating the same day over and over.",
    releaseDate: "1993-02-11",
    genres: [10749, 14, 18, 35],
    id: 137,
    originalTitle: "Groundhog Day",
    title: "Groundhog Day",
    tagline: "Tagline generic: Groundhog Day",
    voteAverage: 1.1,
    voteCount: 549,
    popularity: 6.98,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "Longfellow Deeds lives in a small town, leading a small town kind of life. When a relative dies and leaves Deeds a fortune, Longfellow moves to the big city where he becomes an instant target for everyone. Deeds outwits them all until Babe Bennett comes along. When small-town boy meets big-city girl anything can, and does, happen.",
    releaseDate: "1936-04-12",
    genres: [35, 18],
    id: 24807,
    originalTitle: "Mr. Deeds Goes to Town",
    title: "Mr. Deeds Goes to Town",
    tagline: "Tagline generic: Mr. Deeds Goes to Town",
    voteAverage: 1.0,
    voteCount: 11,
    popularity: 6.95,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "A River Runs Through is a cinematographically stunning true story of Norman Maclean. The story follows Norman and his brother Paul through the experiences of life and growing up, and how their love of fly fishing keeps them together despite varying life circumstances in the untamed west of Montana in the 1920's.",
    releaseDate: "1992-10-09",
    genres: [18],
    id: 293,
    originalTitle: "A River Runs Through It",
    title: "A River Runs Through It",
    tagline: "Tagline generic: A River Runs Through It",
    voteAverage: 1.0,
    voteCount: 69,
    popularity: 6.75,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      'This Christmas movie highlights the technological advances of operations at the North Pole, revealing how Santa and his vast army of highly trained elves produce gifts and distribute them around the world in one night. However, every operation has a margin of error… When one of 600 million children to receive a gift from Santa on Christmas Eve is missed, it is deemed "acceptable" to all but one, Arthur. Arthur Claus is Santa’s misfit son who executes an unauthorized rookie mission to get the last present half way around the globe before dawn on Christmas morning.',
    releaseDate: "2011-11-23",
    genres: [18, 16, 10751, 35],
    id: 51052,
    originalTitle: "Arthur Christmas",
    title: "Arthur Christmas",
    tagline: "Tagline generic: Arthur Christmas",
    voteAverage: 1.0,
    voteCount: 102,
    popularity: 6.72,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "Football coach Harold Jones befriends Radio, a mentally-challenged man who becomes a student at T.L. Hanna High School in Anderson, South Carolina. Their friendship extends over several decades, where Radio transforms from a shy, tormented man into an inspiration to his community.",
    releaseDate: "2003-10-24",
    genres: [18],
    id: 13920,
    originalTitle: "Radio",
    title: "Radio",
    tagline: "Tagline generic: Radio",
    voteAverage: 1.0,
    voteCount: 36,
    popularity: 6.71,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      'Amy is only 13 years old when her mother is killed. She goes to Canada to live with her father, an eccentric inventor whom she barely knows. Amy is miserable in her new life... until she discovers a nest of goose eggs that were abandoned when a local forest is torn down. The eggs hatch and Amy becomes "Mama Goose". When Winter comes, Amy, and her dad must find a way to lead the birds South...',
    releaseDate: "1996-09-13",
    genres: [28, 12, 18, 10751],
    id: 11076,
    originalTitle: "Fly Away Home",
    title: "Fly Away Home",
    tagline: "Tagline generic: Fly Away Home",
    voteAverage: 1.0,
    voteCount: 13,
    popularity: 6.69,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    posterPath: null,
    overview:
      "With their father away as a chaplain in the Civil War, Jo, Meg, Beth and Amy grow up with their mother in somewhat reduced circumstances. They are a close family who inevitably have their squabbles and tragedies. But the bond holds even when, later, male friends start to become a part of the household.",
    releaseDate: "1994-12-21",
    genres: [18, 10749],
    id: 9587,
    originalTitle: "Little Women",
    title: "Little Women",
    tagline: "Tagline generic: Little Women",
    voteAverage: 1.0,
    voteCount: 50,
    popularity: 6.65,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 206647,
    title: "Spectre",
    originalTitle: "Spectre",
    overview:
      "A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.",
    posterPath: "/hE24GYddaxB9MVZl1CaiI86M3kp.jpg",
    tagline: "Tagline generic: Little Women",
    genres: [28, 12, 80],
    voteCount: 2956,
    voteAverage: 4.090211,
    popularity: 6.65,
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
    releaseDate: "2015-10-26",
  },
  {
    id: 22,
    title: "The Matrix Reloaded",
    originalTitle: "The Matrix Reloaded",
    tagline: "Generic tagline The Matrix Reloaded",
    overview:
      "Six months after the events depicted in The Matrix, Neo has proved to be a good omen for the free humans, as more and more humans are being freed from the matrix and brought to Zion, the one and only stronghold of the Resistance. Neo himself has discovered his superpowers including super speed, ability to see the codes of the things inside the matrix and a certain degree of pre-cognition. But a nasty piece of news hits the human resistance: 250,000 machine sentinels are digging to Zion and would reach them in 72 hours. As Zion prepares for the ultimate war, Neo, Morpheus and Trinity are advised by the Oracle to find the Keymaker who would help them reach the Source. Meanwhile Neo's recurrent dreams depicting Trinity's death have got him worried and as if it was not enough, Agent Smith has somehow escaped deletion, has become more powerful than before and has fixed Neo as his next target.",
    posterPath: "/ezIurBz2fdUc68d98Fp9dRf5ihv.jpg",
    genres: [12, 28, 53, 878],
    voteCount: 2187,
    voteAverage: 3.41123,
    popularity: 3.41123,
    releaseDate: "2003-05-15",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 23,
    title: "The Matrix Revolutions",
    originalTitle: "The Matrix Revolutions",
    tagline: "Generic tagline The Matrix Revolutions",
    overview:
      "The human city of Zion defends itself against the massive invasion of the machines as Neo fights to end the war at another front while also opposing the rogue Agent Smith.",
    posterPath: "/sKogjhfs5q3azmpW7DFKKAeLEG8.jpg",
    genres: [12, 28, 53, 878],
    voteCount: 1971,
    voteAverage: 3.043018,
    popularity: 3.043018,
    releaseDate: "2003-11-05",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 24,
    title: "The Transporter",
    originalTitle: "The Transporter",
    tagline: "Generic tagline The Transporter",
    overview:
      "Former Special Forces officer Frank Martin will deliver anything to anyone for the right price, and his no-questions-asked policy puts him in high demand. But when he realizes his latest cargo is alive, it sets in motion a dangerous chain of events. The bound and gagged Lai is being smuggled to France by a shady American businessman, and Frank works to save her as his own illegal activities are uncovered by a French detective.",
    posterPath: "/vD5plFV1ec9CSIsdlPe9icCDRTL.jpg",
    genres: [28, 80, 53],
    voteCount: 988,
    voteAverage: 2.99031,
    popularity: 2.99031,
    releaseDate: "2002-10-02",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 25,
    title: "Chinese Zodiac",
    originalTitle: "Chinese Zodiac",
    tagline: "Generic tagline Chinese Zodiac",
    overview:
      "Asian Hawk (Jackie Chan) leads a mercenary team to recover several lost artifacts from the Old Summer Palace, the bronze heads of the 12 Chinese Zodiac animals which were sacked by the French and British armies from the imperial Summer Palace in Beijing in 1860. Assisted by a Chinese student and a Parisian lady, Hawk stops at nothing to accomplish the mission.",
    posterPath: "/tCUEJ6Svr9eqcUOpxlRbFKlEVqm.jpg",
    genres: [28, 12],
    voteCount: 181,
    voteAverage: 2.325203,
    popularity: 2.325203,
    releaseDate: "2012-12-20",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 26,
    title: "New York, I Love You",
    originalTitle: "New York, I Love You",
    tagline: "Generic tagline New York, I Love You",
    overview:
      "Ten vignettes in New York City: a pickpocket meets his match; a young Hasidic woman, on the eve of her marriage, reveals herself to an Indian businessman; a writer tries a pick-up line; an artist seeks a model; a composer needs to read; two women connect; a man takes a child to Central Park; lovers meet; a couple takes a walk on their anniversary; a kid goes to the prom with a girl in a wheelchair; a retired singer contemplates suicide. There are eight million stories in the naked city: these have been ten of them.",
    posterPath: "/roKhZLvRRzqdVY9rvDv1i5ZAmmx.jpg",
    genres: [18, 35, 10749],
    voteCount: 101,
    voteAverage: 1.989928,
    popularity: 1.989928,
    releaseDate: "2008-09-01",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 27,
    title: "The Wolf of Wall Street",
    originalTitle: "The Wolf of Wall Street",
    tagline: "Generic tagline The Wolf of Wall Street",
    overview:
      "A New York stockbroker refuses to cooperate in a large securities fraud case involving corruption on Wall Street, corporate banking world and mob infiltration. Based on Jordan Belfort's autobiography.",
    posterPath: "/vK1o5rZGqxyovfIhZyMELhk03wO.jpg",
    genres: [80, 18, 35],
    voteCount: 3602,
    voteAverage: 6.013736,
    popularity: 6.013736,
    releaseDate: "2013-12-25",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 28,
    title: "Focus",
    originalTitle: "Focus",
    tagline: "Generic tagline Focus",
    overview:
      "A veteran grifter takes a young, attractive woman under his wing, but things get complicated when they become romantically involved.",
    posterPath: "/9IElGiLkxPLUWZ3avy31bNSG3Tq.jpg",
    genres: [10749, 35, 80, 18],
    voteCount: 1639,
    voteAverage: 3.90442,
    popularity: 3.90442,
    releaseDate: "2015-02-25",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 29,
    title: "Suicide Squad",
    originalTitle: "Suicide Squad",
    tagline: "Generic tagline Suicide Squad",
    overview:
      "From DC Comics comes the Suicide Squad, an antihero team of incarcerated supervillains who act as deniable assets for the United States government, undertaking high-risk black ops missions in exchange for commuted prison sentences.",
    posterPath: "/e1mjopzAS2KNsvpbpahQ1a6SkSn.jpg",
    genres: [14, 28, 80],
    voteCount: 1466,
    voteAverage: 48.261451,
    popularity: 48.261451,
    releaseDate: "2016-08-03",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 30,
    title: "Fast & Furious 6",
    originalTitle: "Fast & Furious 6",
    tagline: "Generic tagline Fast & Furious 6",
    overview:
      "Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries: Dominic unexpectedly gets convoluted also facing his presumed deceased girlfriend, Letty.",
    posterPath: "/b9gTJKLdSbwcQRKzmqMq3dMfRwI.jpg",
    genres: [28, 53, 80],
    voteCount: 4233,
    voteAverage: 1.737593,
    popularity: 1.737593,
    releaseDate: "2013-05-06",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 31,
    title: "Furious 7",
    originalTitle: "Furious 7",
    tagline: "Generic tagline Furious 7",
    overview:
      "Deckard Shaw seeks revenge against Dominic Toretto and his family for his comatose brother.",
    posterPath: "/dCgm7efXDmiABSdWDHBDBx2jwmn.jpg",
    genres: [28, 80, 53],
    voteCount: 2718,
    voteAverage: 13.659073,
    popularity: 13.659073,
    releaseDate: "2015-04-01",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 32,
    title: "The Fast and the Furious",
    originalTitle: "The Fast and the Furious",
    tagline: "Generic tagline The Fast and the Furious",
    overview:
      "Domenic Toretto is a Los Angeles street racer suspected of masterminding a series of big-rig hijackings. When undercover cop Brian O'Conner infiltrates Toretto's iconoclastic crew, he falls for Toretto's sister and must choose a side: the gang or the LAPD.",
    posterPath: "/x4So4OkqnjfOSBCCNd5uosMmQiB.jpg",
    genres: [28, 80, 53],
    voteCount: 2375,
    voteAverage: 1.651117,
    popularity: 1.651117,
    releaseDate: "2001-06-18",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 33,
    title: "Terminator Genisys",
    originalTitle: "Terminator Genisys",
    tagline: "Generic tagline Terminator Genisys",
    overview:
      "The year is 2029. John Connor, leader of the resistance continues the war against the machines. At the Los Angeles offensive, John's fears of the unknown future begin to emerge when TECOM spies reveal a new plot by SkyNet that will attack him from both fronts; past and future, and will ultimately change warfare forever.",
    posterPath: "/5JU9ytZJyR3zmClGmVm9q4Geqbd.jpg",
    genres: [878, 28, 53, 12],
    voteCount: 2334,
    voteAverage: 13.438976,
    popularity: 13.438976,
    releaseDate: "2015-06-23",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 34,
    title: "Me Before You",
    originalTitle: "Me Before You",
    tagline: "Generic tagline Me Before You",
    overview:
      "A small town girl is caught between dead-end jobs. A high-profile, successful man becomes wheelchair bound following an accident. The man decides his life is not worth living until the girl is hired for six months to be his new caretaker. Worlds apart and trapped together by circumstance, the two get off to a rocky start. But the girl becomes determined to prove to the man that life is worth living and as they embark on a series of adventures together, each finds their world changing in ways neither of them could begin to imagine.",
    posterPath: "/kJ6eMKlY1I8vVUosWtfP7qbCugL.jpg",
    genres: [18, 10749],
    voteCount: 501,
    voteAverage: 8.553487,
    popularity: 8.553487,
    releaseDate: "2016-03-03",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 35,
    title: "San Andreas",
    originalTitle: "San Andreas",
    tagline: "Generic tagline San Andreas",
    overview:
      "In the aftermath of a massive earthquake in California, a rescue-chopper pilot makes a dangerous journey across the state in order to rescue his estranged daughter.",
    posterPath: "/qey0tdcOp9kCDdEZuJ87yE3crSe.jpg",
    genres: [28, 18, 53],
    voteCount: 1866,
    voteAverage: 6.990629,
    popularity: 6.990629,
    releaseDate: "2015-05-27",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
  {
    id: 36,
    title: "Percy Jackson & the Olympians: The Lightning Thief",
    originalTitle: "Percy Jackson & the Olympians: The Lightning Thief",
    tagline:
      "Generic tagline Percy Jackson & the Olympians: The Lightning Thief",
    overview:
      "Accident prone teenager, Percy discovers he's actually a demi-God, the son of Poseidon, and he is needed when Zeus' lightning is stolen. Percy must master his new found skills in order to prevent a war between the Gods that could devastate the entire world.",
    posterPath: "/5NhyXkodMzDRW8uqtPqlxJsoBhf.jpg",
    genres: [12, 14, 10751],
    voteCount: 1047,
    voteAverage: 3.835911,
    popularity: 3.835911,
    releaseDate: "2010-02-01",
    status: "Released",
    revenue: 1234596,
    budget: 1987540,
  },
]);
export default movies;
